### ISSUE TITLE
negate function behaves differently to that of normal Word* types?

### ISSUE THREAD

**Issue by rod-lin** [idontgetoutmuch/largeword#15]
Hi, I was using `Word256` and found that the `negate` function is defined as `id` in the package.

Is that inconsistent with the behavior of `Word*` in the base package?
e.g. `-1` gives the result of `(complement 1 + 1)` for the normal Word* but in your implementaion, it yields `1`

**Comment by idontgetoutmuch** [comment]
That does indeed look odd.
